INSERT INTO Professor (CodProf, NomeProf) VALUES (1,"Aline Andrade");
INSERT INTO Professor (CodProf, NomeProf) VALUES (2,"Antonio Apolinario");
INSERT INTO Professor (CodProf, NomeProf) VALUES (3,"Cassio Prazeres");
INSERT INTO Professor (CodProf, NomeProf) VALUES (4,"Christina von Flach");
INSERT INTO Professor (CodProf, NomeProf) VALUES (5,"Claudio SantAnna");
INSERT INTO Professor (CodProf, NomeProf) VALUES (6,"Danilo Coimbra");
INSERT INTO Professor (CodProf, NomeProf) VALUES (7,"Debora Abdalla Santos");
INSERT INTO Professor (CodProf, NomeProf) VALUES (8,"Ecivaldo Matos");
INSERT INTO Professor (CodProf, NomeProf) VALUES (9,"Eduardo Santana de Almeida");
INSERT INTO Professor (CodProf, NomeProf) VALUES (10,"Frederido Araujo Durao");
INSERT INTO Professor (CodProf, NomeProf) VALUES (11,"George Lima");
INSERT INTO Professor (CodProf, NomeProf) VALUES (12,"Gustavo Figueiredo");
INSERT INTO Professor (CodProf, NomeProf) VALUES (13,"Ivan Machado");
INSERT INTO Professor (CodProf, NomeProf) VALUES (14,"Karl Aguero");
INSERT INTO Professor (CodProf, NomeProf) VALUES (15,"Leobino Sampaio");
INSERT INTO Professor (CodProf, NomeProf) VALUES (16,"Luiz Brandão");
INSERT INTO Professor (CodProf, NomeProf) VALUES (17,"Manoel Mendonça");
INSERT INTO Professor (CodProf, NomeProf) VALUES (18,"Marlo Souza");
INSERT INTO Professor (CodProf, NomeProf) VALUES (19,"Maycon Peixoto");
INSERT INTO Professor (CodProf, NomeProf) VALUES (20,"Paul Regnier");
INSERT INTO Professor (CodProf, NomeProf) VALUES (21,"Rafael Melo");
INSERT INTO Professor (CodProf, NomeProf) VALUES (22,"Ricardo Rios");
INSERT INTO Professor (CodProf, NomeProf) VALUES (23,"Rita Maciel");
INSERT INTO Professor (CodProf, NomeProf) VALUES (24,"Roberto Parente");
INSERT INTO Professor (CodProf, NomeProf) VALUES (25,"Rodrigo Souza");
INSERT INTO Professor (CodProf, NomeProf) VALUES (26,"Rubisley Lemes");
INSERT INTO Professor (CodProf, NomeProf) VALUES (27,"Steffen Lewitzka");
INSERT INTO Professor (CodProf, NomeProf) VALUES (28,"Tatiane Rios");
INSERT INTO Professor (CodProf, NomeProf) VALUES (29,"Tiago Januario");
INSERT INTO Professor (CodProf, NomeProf) VALUES (30,"Vaninha Vieira");
INSERT INTO Professor (CodProf, NomeProf) VALUES (31,"Vinicius Petrucci");
INSERT INTO Professor (CodProf, NomeProf) VALUES (32,"Marcos Ennes Barreto");