INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121716','Lucas Cardoso da Silva','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('215115726','Luis Paulo da Silva Carvalho','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216220951','Roselane Santana Silva','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219752','Gabriel R‚gis Biurrum','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('217123304','Marco Antonio Costa Simäes','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219768','Thiago Miranda dos Santos Souza','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121798','Gabriela Oliveira Mota da Silva','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219756','Juvenal Constantino de Macedo Junior','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121711','Fabricio de Freitas Cardim','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219755','Juracy Bertoldo Santos Junior','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216221521','Alberto Pietro Sironi','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('217122979','Leonan Teixeira de Oliveira','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219617','Cleber Jorge Lira de Santana','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('215216441','Erasmo Leite Monteiro','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219750','Carlos Fernando S F de Abreu Neto','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('217123299','Tatiana de Oliveira Silva','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('217123297','Marcos Antonio de Souza Silva','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121806','Val‚ria Argolo Rosa de Queiroz','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('215115714','Ana Maria Paranhos de Amorim','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('217123302','Andr‚ Kazuo Horota','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121463','Nicolli Souza Rios Alves','D');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219757','Leandro Alves de Menezes','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216219749','Bruno Ramos e Silva','M');
INSERT INTO `trablabbd`.`aluno` (`Matricula`,`Nome`,`Nivel`) VALUES ('216121796','Daniel Domingos Alves','D');
