INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MAT045",8,"Processamento de Dados");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MAT115",8,"Introdução ao Processamento de Dados");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MAT220",10,"Empreendedores em Informática");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA37",8,"Introdução a Lógica de Programação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA38",1,"Projeto de Circuitos Lógicos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA39",3,"Seminários de Introdução ao Curso");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA40",8,"Estrutura de Dados e Algoritmos I");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA47",6,"Lógica para Computação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA48",1,"Arquitetura de Computadores");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA50",6,"Linguagens Formais e Autômatos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA51",6,"Teoria da Computação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA52",6,"Análise e Projeto de Algoritmos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA53",6,"Teoria dos Grafos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA55",5,"Programação Orientada a Objetos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA56",5,"Paradigmas de Linguagens de Programação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA57",8,"Laboratório de Programação I");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA58",10,"Sistemas Operacionais");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA59",9,"Redes de Computadores I");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA60",2,"Banco de Dados");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA61",6,"Compiladores");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA62",5,"Engenharia de Software I");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA63",5,"Engenharia de Software II");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA64",7,"Inteligência Artificial");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA65",4,"Computação Gráfica");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA68",3,"Computador, Ética e Sociedade");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA76",5,"Linguagens para Aplicação Comercial");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATA86",9,"Tópicos em Redes de Computadores");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATB14",5,"Laboratório de Engenharia de Software");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATB16",7,"Laboratório de Inteligência Artificial");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATB17",4,"Laboratório de Computação Gráfica e Processamento de Imagens");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATB24",10,"Robótica Inteligente");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATB26",10,"Tópicos em sistemas multimídia");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATC53",3,"ACCS: Onda solidária de inclusão digital");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATC73",6,"Introdução à Lógica Matemática");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATC89",10,"Aplicações para Dispositivos Móveis");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATC96",10,"Organização, Gerenciamento e Recuperação da Informação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATD02",10,"Tópicos em Sistemas de Informação");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATD04",8,"Estrutura de Dados");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATD74",6,"Algoritmos e Grafos");
INSERT INTO Disciplina (CodDisc, CodArea, NomeDisc) VALUES ("MATF34",8,"ACCS: Programação Competitiva");